spring:
  application:
    name: srvconfigmap
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      config:
        enabled: true
        name: config-map-test
        namespace: default
        sources:
          - namespace: default
          - name: config-map-test
      reload:
        enabled: true
        strategy: refresh
        mode: event
        monitoring-config-maps: true

myconfig:
  varTest1: ${myconfig.chave1:vazia}
  varTest2: ${myconfig.chave2:vazia}
